/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OPP;


import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akmal Kurniawan
 */
public class kasir_page extends javax.swing.JFrame {
    private Profile profile;

    /**
     * Creates new form kasir
     */
    public kasir_page(OPP.Profile P) {
        this.profile = profile;
        initComponents();
    }

    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtProduk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUangBayar = new javax.swing.JTextField();
        tombolCheckout = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        lblTotalHarga = new javax.swing.JLabel();
        lbluangKembali = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TOKO SUMBER SEJAHTERA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Kota Tegal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(635, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        txtProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdukActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Barang", "Qty", "Harga"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");

        jLabel3.setText("Tanggal");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Kembalian");

        jLabel6.setText("Total Harga");

        jLabel7.setText("Bayar");

        txtUangBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUangBayarKeyReleased(evt);
            }
        });

        tombolCheckout.setText("Bayar");
        tombolCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCheckoutActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Cetak Transaksi");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nama Barang");

        lblTotalHarga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalHarga.setText("Rp");

        lbluangKembali.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbluangKembali.setText("Rp");

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane2.setViewportView(textArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField6)
                            .addComponent(lbluangKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUangBayar)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tombolCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButton2)))
                                .addGap(0, 87, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblTotalHarga))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbluangKembali)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        delFromCart();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdukActionPerformed
        addProductToTable();
    }//GEN-LAST:event_txtProdukActionPerformed

    private void tombolCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCheckoutActionPerformed
        
    }//GEN-LAST:event_tombolCheckoutActionPerformed

    private void txtUangBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangBayarKeyReleased
        endsKetikUangPembayaran();
    }//GEN-LAST:event_txtUangBayarKeyReleased

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
    tampilkanTransaksi();
        cetakTransaksi();
        resetForm();

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(kasir_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(kasir_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(kasir_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(kasir_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Membuat data dummy untuk pengujian
            Profile P = new Profile();
            P.setId(1);
            P.setFullname("Kasir User");
            P.setUsername("kasir1");
            P.setPassword("password2");
            P.setLevel("kasir");

            // Membuka halaman kasir
            new kasir_page(P).setVisible(true);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JLabel lbluangKembali;
    private javax.swing.JTextArea textArea;
    private javax.swing.JToggleButton tombolCheckout;
    private javax.swing.JTextField txtProduk;
    private javax.swing.JTextField txtUangBayar;
    // End of variables declaration//GEN-END:variables
private void addProductToTable() {
    try {
        // Listen for changes in the table model
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addTableModelListener((TableModelEvent e) -> {
            int row = e.getFirstRow();
            int column = e.getColumn();
            if (row >= 0 && column >= 0) {
                updateTotalHarga();
                endsKetikUangPembayaran();
            }
        });

        // Fetch product details based on the input code
        String kode = txtProduk.getText();
        Connection K = OPP.Koneksi.Go();
        Statement S = K.createStatement();
        String Q = "SELECT * FROM produk WHERE Kode_produk='" + kode + "'";
        ResultSet R = S.executeQuery(Q);

        while (R.next()) {
            int id = R.getInt("id");
            String nama = R.getString("Nama_Produk");
            String harga = R.getString("Harga_Jual");

            // Check if the product already exists in the table
            int row = jTable1.getRowCount();
            boolean ada = false;
            int QTY = 0;
            int baris = 0;

            if (row > 0) {
                for (int i = 0; i < row; i++) {
                    // Safely get the value at the first column
                    Object value = jTable1.getValueAt(i, 0);
                    int id_produk = (value != null) ? Integer.parseInt(value.toString()) : -1;  // Safely handle null
                    if (id_produk == id) {
                        ada = true;
                        baris = i;
                        // Safely get the value at the third column
                        Object qtyValue = jTable1.getValueAt(i, 2);
                        QTY = (qtyValue != null) ? Integer.parseInt(qtyValue.toString()) + 1 : 1;  // Safely handle null
                        break;
                    }
                }

                if (ada) {
                    jTable1.setValueAt(QTY, baris, 2);
                    updateTotalHarga();
                } else {
                    Object[] data = {id, nama, 1, harga};
                    model.addRow(data);
                }
            } else {
                Object[] data = {id, nama, 1, harga};
                model.addRow(data);
            }
        }

        // Update the total price and other fields
        updateTotalHarga();
        endsKetikUangPembayaran();

    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }
}


    private void updateTotalHarga() {
    double total = 0.0;
    int rowCount = jTable1.getRowCount();

    for (int i = 0; i < rowCount; i++) {
        // Safely check if the cell contains a value
        Object priceValue = jTable1.getValueAt(i, 3); // Assuming price is in column 3
        Object qtyValue = jTable1.getValueAt(i, 2); // Assuming quantity is in column 2

        if (priceValue != null && qtyValue != null) {
            try {
                double price = Double.parseDouble(priceValue.toString());
                int qty = Integer.parseInt(qtyValue.toString());
                total += price * qty;
            } catch (NumberFormatException e) {
                // Handle any number parsing errors if needed
                System.out.println("Error parsing price or quantity at row " + i);
            }
        }
    }

    // Update the total price display (assuming you have a JLabel or JTextField to show the total)
    lblTotalHarga.setText("Total: " + total);
}


    private void delFromCart() {
        int b = jTable1.getSelectedRow();
        if (b != -1) {
            DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            m.removeRow(b);
            
            
            updateTotalHarga();
            endsKetikUangPembayaran();
        } else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data");
        }
    }
    private void resetForm() {
    lbluangKembali.setText("Rp 0");
    txtUangBayar.setText("");
    lblTotalHarga.setText("Rp 0");
    // Reset tabel
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    tombolCheckout.setEnabled(false);
}
    private void tampilkanTransaksi() {
    StringBuilder transaksi = new StringBuilder();
    transaksi.append("=== Rincian Transaksi ===\n");

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        transaksi.append(model.getValueAt(i, 0)).append(" - ");
        transaksi.append(model.getValueAt(i, 1)).append(" x ");
        transaksi.append(model.getValueAt(i, 2)).append(" = ");
        transaksi.append(model.getValueAt(i, 3)).append("\n");
    }

    transaksi.append("\nTotal: ").append(lblTotalHarga.getText());
    transaksi.append("\nBayar: Rp ").append(txtUangBayar.getText());
    transaksi.append("\nKembali: ").append(lbluangKembali.getText()).append("\n");
    transaksi.append("=========================\n");

    textArea.setText(transaksi.toString());
}

private void cetakTransaksi() {
    try {
        boolean complete = textArea.print();
        if (complete) {
            JOptionPane.showMessageDialog(null, "Transaksi berhasil dicetak!");
        } else {
            JOptionPane.showMessageDialog(null, "Pencetakan dibatalkan.");
        }
    } catch (PrinterException ex) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mencetak: " + ex.getMessage());
    }
}



    private void endsKetikUangPembayaran() {
    int r = jTable1.getRowCount();
    if (r > 0) {
        String lbl = lblTotalHarga.getText(); // Example: "Rp 12000"
        
        // Remove the "Rp " part and parse the remaining number
        String[] arrayHarga = lbl.split(" ");
        double harga = 0;

        try {
            harga = Double.parseDouble(arrayHarga[1]);  // Use Double.parseDouble to handle decimal values
        } catch (NumberFormatException e) {
            System.out.println("Error parsing harga: " + e.getMessage());
        }

        String bayar = txtUangBayar.getText();
        if (!bayar.isEmpty()) {
            double uangbayar = 0;
            try {
                uangbayar = Double.parseDouble(bayar);  // Parse bayar as double to handle decimal payments
            } catch (NumberFormatException e) {
                System.out.println("Error parsing uangbayar: " + e.getMessage());
            }

            double uangkembali = uangbayar - harga;  // Calculate change

            // Format the change as Rp
            lbluangKembali.setText("Rp " + uangkembali);

            if (uangbayar >= harga) {
                tombolCheckout.setEnabled(true); // Enable checkout if the payment is sufficient
            } else {
                tombolCheckout.setEnabled(false); // Disable checkout if the payment is insufficient
            }
        } else {
            lbluangKembali.setText("Rp " + 0); // If no payment, set change to 0
            tombolCheckout.setEnabled(false); // Disable checkout if no payment
        }
    }
}

}

